import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const languages = [
  { name: 'English', code: 'en-IN' },
  { name: 'Hindi', code: 'hi-IN' },
  { name: 'Bengali', code: 'bn-IN' },
  { name: 'Tamil', code: 'ta-IN' },
  { name: 'Telugu', code: 'te-IN' },
  { name: 'Marathi', code: 'mr-IN' },
  { name: 'Gujarati', code: 'gu-IN' },
  { name: 'Kannada', code: 'kn-IN' },
  { name: 'Malayalam', code: 'ml-IN' },
  { name: 'Punjabi', code: 'pa-IN' }
];

export const translations = {
  English: {
    heroTitle: "Empowering Democracy Through AI Intelligence",
    heroDesc: "Experience a frictionless voting journey with VoteWise. Our AI ensures every citizen is informed, registered, and ready to make a difference.",
    beginJourney: "Begin Your Journey",
    locateStations: "Locate Stations",
    digitalJourney: "The Digital Journey",
    eligibility: "Eligibility",
    registration: "Registration",
    findBooth: "Find Booth",
    castVote: "Cast Vote",
    dashboard: "Dashboard",
    journey: "Journey",
    stations: "Stations",
    candidates: "Candidates",
    aiAssistant: "AI Assistant",
    joinNow: "Join Now",
    logout: "Logout",
    account: "Account",
    newJourney: "New Journey",
    aiAssistants: "AI Assistants",
    voterEducation: "Voter Education",
    realTimeUpdates: "Real-time Updates",
    yourRecents: "Your Recents",
    analyzeData: "Analyzing Election Data...",
    askAnything: "Ask anything about Indian Elections...",
    botWelcomeTitle: "How can VoteWise help your democratic journey?",
    botWelcomeSub: "Your AI Election Assistant",
    suggestion1: "Register to Vote",
    suggestion2: "Find Polling Booth",
    suggestion3: "Election Quiz",
    suggestion4: "Candidate List"
  },
  Hindi: {
    heroTitle: "AI बुद्धिमत्ता के माध्यम से लोकतंत्र को सशक्त बनाना",
    heroDesc: "वोटवाइज के साथ एक निर्बाध मतदान यात्रा का अनुभव करें। हमारा एआई यह सुनिश्चित करता है कि हर नागरिक सूचित, पंजीकृत और बदलाव लाने के लिए तैयार हो।",
    beginJourney: "अपनी यात्रा शुरू करें",
    locateStations: "केंद्रों का पता लगाएं",
    digitalJourney: "डिजिटल यात्रा",
    eligibility: "पात्रता",
    registration: "पंजीकरण",
    findBooth: "बूथ खोजें",
    castVote: "वोट डालें",
    dashboard: "डैशबोर्ड",
    journey: "यात्रा",
    stations: "केंद्र",
    candidates: "उम्मीदवार",
    aiAssistant: "एआई सहायक",
    joinNow: "अभी जुड़ें",
    logout: "लॉगआउट",
    botWelcomeTitle: "वोटवाइज आपकी लोकतांत्रिक यात्रा में कैसे मदद कर सकता है?",
    suggestion1: "पंजीकरण करें",
    suggestion2: "बूथ खोजें",
    suggestion3: "प्रश्नोत्तरी",
    suggestion4: "उम्मीदवार"
  },
  Bengali: {
    heroTitle: "এআই বুদ্ধিমত্তার মাধ্যমে গণতন্ত্রের ক্ষমতায়ন",
    heroDesc: "ভোটওয়াইজের সাথে একটি নিরবচ্ছিন্ন ভোটদান ভ্রমণের অভিজ্ঞতা নিন।",
    beginJourney: "আপনার যাত্রা শুরু করুন",
    locateStations: "কেন্দ্রগুলি খুঁজুন",
    digitalJourney: "ডিজিটাল যাত্রা",
    eligibility: "যোগ্যতা",
    registration: "নিবন্ধন",
    findBooth: "বুথ খুঁজুন",
    castVote: "ভোট দিন",
    dashboard: "ড্যাশবোর্ড",
    journey: "যাত্রা",
    stations: "স্টেশন",
    candidates: "প্রার্থী",
    aiAssistant: "এআই সহকারী",
    joinNow: "এখনই যোগ দিন",
    logout: "লগআউট",
    botWelcomeTitle: "ভোটওয়াইজ আপনার গণতান্ত্রিক যাত্রায় কীভাবে সাহায্য করতে পারে?",
    suggestion1: "নিবন্ধন করুন",
    suggestion2: "বুথ খুঁজুন",
    suggestion3: "কুইজ",
    suggestion4: "প্রার্থী"
  },
  Tamil: {
    heroTitle: "AI நுண்ணறிவு மூலம் ஜனநாயகத்தை மேம்படுத்துதல்",
    heroDesc: "VoteWise உடன் உராய்வில்லாத வாக்களிப்பு பயணத்தை அனுபவியுங்கள்.",
    beginJourney: "உங்கள் பயணத்தைத் தொடங்குங்கள்",
    locateStations: "நிலையங்களைக் கண்டறியவும்",
    digitalJourney: "டிஜிட்டல் பயணம்",
    eligibility: "தகுதி",
    registration: "பதிவு",
    findBooth: "பூத் கண்டுபிடி",
    castVote: "வாக்களியுங்கள்",
    dashboard: "டாஷ்போர்டு",
    journey: "பயணம்",
    stations: "நிலையங்கள்",
    candidates: "வேட்பாளர்கள்",
    aiAssistant: "AI உதவியாளர்",
    joinNow: "இப்போது இணையுங்கள்",
    logout: "வெளியேறு",
    botWelcomeTitle: "VoteWise உங்கள் ஜனநாயகப் பயணத்திற்கு எவ்வாறு உதவ முடியும்?",
    suggestion1: "பதிவு செய்க",
    suggestion2: "பூத் காண்க",
    suggestion3: "வினாடி వినా",
    suggestion4: "வேட்பாளர்"
  },
  Telugu: {
    heroTitle: "AI మేధస్సు ద్వారా ప్రజాస్వామ్యాన్ని బలోపేతం చేయడం",
    heroDesc: "VoteWise తో సులభమైన ఓటింగ్ ప్రయాణాన్ని అనుభవించండి.",
    beginJourney: "మీ ప్రయాణాన్ని ప్రారంభించండి",
    locateStations: "కేంద్రాలను గుర్తించండి",
    digitalJourney: "డిజిటల్ ప్రయాణం",
    eligibility: "అర్హత",
    registration: "నమోదు",
    findBooth: "బూత్ కనుగొనండి",
    castVote: "ఓటు వేయండి",
    dashboard: "డాష్‌బోర్డ్",
    journey: "ప్రయాణం",
    stations: "కేంద్రాలు",
    candidates: "అభ్యర్థులు",
    aiAssistant: "AI సహాయకుడు",
    joinNow: "ఇప్పుడే చేరండి",
    logout: "లాగ్ అవుట్",
    botWelcomeTitle: "మీ ప్రజాస్వామ్య ప్రయాణంలో VoteWise ఎలా సహాయపడుతుంది?",
    suggestion1: "నమోదు చేసుకోండి",
    suggestion2: "బూత్ కనుగొనండి",
    suggestion3: "క్విజ్",
    suggestion4: "అభ్యర్థులు"
  },
  Marathi: {
    heroTitle: "AI बुद्धिमत्तेद्वारे लोकशाहीचे सक्षમીकरण",
    heroDesc: "VoteWise सह सुलभ मतदान प्रवासाचा अनुभव घ्या.",
    beginJourney: "तुमचा प्रवास सुरू करा",
    locateStations: "केंद्र शोधा",
    digitalJourney: "डिजिटल प्रवास",
    eligibility: "पात्रता",
    registration: "नोंदणी",
    findBooth: "बूथ शोधा",
    castVote: "मतदान करा",
    dashboard: "डॅशबोर्ड",
    journey: "प्रवास",
    stations: "केंद्र",
    candidates: "उमेदवार",
    aiAssistant: "AI सहाय्यक",
    joinNow: "आता सामील व्हा",
    logout: "लॉगआउट",
    botWelcomeTitle: "तुमच्या लोकशाही प्रवासात VoteWise कशी मदत करू शकते?",
    suggestion1: "नोंदणी करा",
    suggestion2: "बूথ शोधा",
    suggestion3: "चाचणी",
    suggestion4: "उमेदवार"
  },
  Gujarati: {
    heroTitle: "AI બુદ્ધિ દ્વારા લોકશાહીનું સશક્તિકરણ",
    heroDesc: "VoteWise સાથે સરળ મતદાન પ્રવાસનો અનુભવ કરો.",
    beginJourney: "તમારી યાત્રા શરૂ કરો",
    locateStations: "કેન્દ્રો શોધો",
    digitalJourney: "ડિજિટલ યાત્રા",
    eligibility: "પાત્રતા",
    registration: "નોંધણી",
    findBooth: "બૂથ શોધો",
    castVote: "મત આપો",
    dashboard: "ડેશબોર્ડ",
    journey: "યાત્રા",
    stations: "કેન્દ્રો",
    candidates: "ઉમેદવારો",
    aiAssistant: "AI સહાયક",
    joinNow: "અત્યારે જોડાવો",
    logout: "લોગઆઉટ",
    botWelcomeTitle: "તમારી લોકશાહી યાત્રામાં VoteWise કેવી રીતે મદદ કરી શકે?",
    suggestion1: "નોંધણી કરો",
    suggestion2: "બૂથ શોધો",
    suggestion3: "ક્વિઝ",
    suggestion4: "ઉમેદવારો"
  },
  Kannada: {
    heroTitle: "AI ಬುದ್ಧಿಮತ್ತೆಯ ಮೂಲಕ ಪ್ರಜಾಪ್ರಭುತ್ವದ ಸಬಲೀಕರಣ",
    heroDesc: "VoteWise ನೊಂದಿಗೆ ಸುಲಭವಾದ ಮತದಾನದ ಪ್ರಯಾಣವನ್ನು ಅನುಭವಿಸಿ.",
    beginJourney: "ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    locateStations: "ಕೇಂದ್ರಗಳನ್ನು ಹುಡುಕಿ",
    digitalJourney: "ಡಿಜಿಟಲ್ ಪ್ರಯಾಣ",
    eligibility: "ಅರ್ಹತೆ",
    registration: "ನೋಂದಣಿ",
    findBooth: "ಬೂತ್ ಹುಡುಕಿ",
    castVote: "ಮತ ಚಲಾಯಿಸಿ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    journey: "ಪ್ರಯಾಣ",
    stations: "ಕೇಂದ್ರಗಳು",
    candidates: "ಅಭ್ಯರ್ಥಿಗಳು",
    aiAssistant: "AI ಸಹಾಯಕ",
    joinNow: "ಈಗಲೇ ಸೇರಿ",
    logout: "ಲಾಗ್‌ಔಟ್",
    botWelcomeTitle: "ನಿಮ್ಮ ಪ್ರಜಾಪ್ರಭುತ್ವದ ಪ್ರಯಾಣದಲ್ಲಿ VoteWise ಹೇಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ?",
    suggestion1: "ನೋಂದಾಯಿಸಿ",
    suggestion2: "ಬೂತ್ ಹುಡುಕಿ",
    suggestion3: "ರಸಪ್ರಶ್ನೆ",
    suggestion4: "ಅಭ್ಯರ್ಥಿಗಳು"
  },
  Malayalam: {
    heroTitle: "AI బుద్ధిയിലൂടെ ജനാധിപത്യത്തെ ശാക്തീകരിക്കുന്നു",
    heroDesc: "VoteWise-നൊപ്പം സുഗമമായ വോട്ടിംഗ് അനുഭവം നേടുക.",
    beginJourney: "നിങ്ങളുടെ യാത്ര ആരംഭിക്കുക",
    locateStations: "കേന്ദ്രങ്ങൾ കണ്ടെത്തുക",
    digitalJourney: "ഡിജിറ്റൽ യാത്ര",
    eligibility: "യോഗ്യത",
    registration: "രജിസ്ട്രേഷൻ",
    findBooth: "ബൂത്ത് കണ്ടെത്തുക",
    castVote: "വോട്ട് ചെയ്യുക",
    dashboard: "ഡാഷ്‌ബോർഡ്",
    journey: "യാത്ര",
    stations: "കേന്ദ്രങ്ങൾ",
    candidates: "സ്ഥാനാർത്ഥികൾ",
    aiAssistant: "AI അസിസ്റ്റന്റ്",
    joinNow: "ഇപ്പോൾ ചേരുക",
    logout: "ലോഗ്ഔട്ട്",
    botWelcomeTitle: "നിങ്ങളുടെ ജനാധിപത്യ യാത്രയിൽ VoteWise എങ്ങനെ സഹായിക്കും?",
    suggestion1: "രജിസ്റ്റർ ചെയ്യുക",
    suggestion2: "ബൂത്ത് കണ്ടെത്തുക",
    suggestion3: "ക്വിസ്",
    suggestion4: "സ്ഥാനാർത്ഥികൾ"
  },
  Punjabi: {
    heroTitle: "AI ਬੁੱਧੀ ਦੁਆਰਾ ਲੋਕਤੰਤਰ ਦਾ ਸਸ਼ਕਤੀਕਰਨ",
    heroDesc: "VoteWise ਨਾਲ ਸੁਖਾਲੀ ਵੋਟਿੰਗ ਯਾਤਰਾ ਦਾ ਅਨੁਭਵ ਕਰੋ.",
    beginJourney: "ਆਪਣੀ ਯਾਤਰਾ ਸ਼ੁਰੂ ਕਰੋ",
    locateStations: "ਕੇਂਦਰ ਲੱਭੋ",
    digitalJourney: "ਡਿਜੀਟਲ ਯਾਤਰਾ",
    eligibility: "ਯੋਗਤਾ",
    registration: "ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
    findBooth: "ਬੂਥ ਲੱਭੋ",
    castVote: "ਵੋਟ ਪਾਓ",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    journey: "ਯਾਤਰਾ",
    stations: "ਕੇਂਦਰ",
    candidates: "ਉਮੀਦਵਾਰ",
    aiAssistant: "AI ਸਹਾਇਕ",
    joinNow: "ਹੁਣੇ ਜੁੜੋ",
    logout: "ਲੌਗਆਊਟ",
    botWelcomeTitle: "ਤੁਹਾਡੀ ਲੋਕਤੰਤਰੀ ਯਾਤਰਾ ਵਿੱਚ VoteWise ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹੈ?",
    suggestion1: "ਰਜਿਸਟਰ ਕਰੋ",
    suggestion2: "ਬੂਥ ਲੱਭੋ",
    suggestion3: "ਕਵਿਜ਼",
    suggestion4: "ਉਮੀਦਵਾਰ"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('voteWiseLang') || 'English');

  useEffect(() => {
    localStorage.setItem('voteWiseLang', language);
  }, [language]);

  const t = translations[language] || translations.English;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
